apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:masters
      rolearn: arn:aws:iam::403364721735:role/UdacityFlaskDeployCBKubectlRole
      username: build
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::403364721735:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-1IP687E8E28YS
      username: system:node:{{EC2PrivateDNSName}}
  mapUsers: |
    []
kind: ConfigMap
metadata:
  creationTimestamp: "2021-05-16T01:02:12Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1435"
  selfLink: /api/v1/namespaces/kube-system/configmaps/aws-auth
  uid: 9c1ea6e9-10c9-446f-9ab8-00a399f30c3f
